server:
  port: 11111

eureka:
  client:
    serviceUrl:
      #是否向注册中心注册自己
      register-with-eureka: true
      #是否获取注册表
      fetch-registry: false
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GentleLRW/lrw_cloud.git
          search-paths: 'config-repo/{application}/{profile}/'
          username: GentleLRW
          password: lvrongwu507069
        health:
          repositories:
            check:
              name: lrw_cloud
              label: master
              profiles: dev

