spring:
  profiles:
    include: base
  redis:
    host: 134.175.236.212
    port: 6379
    timeout: 3s
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  sharding-jdbc:
    password: 123456
    url: jdbc:mysql://134.175.236.212:3306/f5cloud_scheduler?zeroDateTimeBehavior=convertToNull&unicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
    username: root
    driverClassName: com.mysql.jdbc.Driver

redisson:
  lock:
    server:
      address: 134.175.236.212
      type: standalone
      password:
      database: 0
      port: 6379

zookeeper:
  lock:
    host: 134.175.236.212
    port: 2181
    rootPath: /lock

