spring:
  profiles:
    include: base
  redis:
    host: 134.175.236.212
    password:
    port: 6379
    timeout: 3s
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms

redisson:
  lock:
    server:
      address: 134.175.236.212
      type: standalone
      password:
      database: 1
      port: 6379

